apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashboard-alertas-tea
  namespace: workshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dashboard-alertas-tea
  template:
    metadata:
      labels:
        app: dashboard-alertas-tea
    spec:
      containers:
        - name: dashboard-alertas-tea
          image: dashboard-alertas-tea:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: dashboard-alertas-tea-config
